import React, { useState, useEffect } from 'react';
import RiskGauge from '../components/RiskGauge';
import RiskBadge from '../components/RiskBadge';
import StatusBadge from '../components/StatusBadge';
import { 
  Search, ShieldAlert, FileText, Building2, User, Activity, 
  Sparkles, MessageSquare, TrendingUp, Brain, Zap, AlertTriangle, ArrowRight
} from 'lucide-react';
import { fetchShapExplanation } from '../services/api';

export default function ClaimsConsole({ claims, selectedClaim, onSelectClaim, onOpenAiModal }) {
  const activeClaim = selectedClaim || claims[0] || {};

  const [search, setSearch] = useState('');
  const [riskFilter, setRiskFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [activeTab, setActiveTab] = useState('intelligence');
  const [shapData, setShapData] = useState(null);
  const [loadingShap, setLoadingShap] = useState(false);

  const [claimStatus, setClaimStatus] = useState(activeClaim.status || 'Escalated');
  const [notes, setNotes] = useState([
    { author: 'Dr. Sarah Jenkins', date: '2026-08-11', text: 'Initial high-risk alert generated by Model A. Flagged for abnormal inpatient billing.' }
  ]);
  const [newNote, setNewNote] = useState('');

  useEffect(() => {
    if (activeTab === 'explainability' && activeClaim.claim_id) {
      setLoadingShap(true);
      fetchShapExplanation(activeClaim.claim_id, activeClaim.provider_id).then(data => {
        setShapData(data);
        setLoadingShap(false);
      });
    }
  }, [activeTab, activeClaim.claim_id, activeClaim.provider_id]);

  const filteredClaims = claims.filter(c => {
    const matchesRisk = riskFilter === 'ALL' || c.risk_level === riskFilter;
    const matchesStatus = statusFilter === 'ALL' || c.status === statusFilter;
    const matchesSearch = 
      c.claim_id.toLowerCase().includes(search.toLowerCase()) ||
      c.provider_name.toLowerCase().includes(search.toLowerCase()) ||
      c.beneficiary_id.toLowerCase().includes(search.toLowerCase());
    return matchesRisk && matchesStatus && matchesSearch;
  });

  const handleAddNote = (e) => {
    e.preventDefault();
    if (!newNote.trim()) return;
    setNotes([...notes, { author: 'Lead SIU Auditor', date: '2026-08-13', text: newNote }]);
    setNewNote('');
  };

  const handleStatusChange = (newStatus) => {
    setClaimStatus(newStatus);
    setNotes(prev => [...prev, { author: 'System Log', date: '2026-08-13', text: `Claim status changed to '${newStatus}'` }]);
  };

  return (
    <div className="h-[calc(100vh-80px)] flex flex-col space-y-4 pb-6">
      
      

      {/* Main Split Layout */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-6 min-h-0 overflow-hidden">
        
        {/* Left Pane: Claims List */}
        <div className="lg:col-span-4 bg-white rounded-xl border border-slate-200 shadow-lg flex flex-col h-full overflow-hidden">
          
          <div className="p-4 border-b border-slate-200 space-y-3 bg-gradient-to-br from-slate-50 to-white">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-navy-900 flex items-center gap-2">
                <FileText className="w-4 h-4 text-brand-blue" />
                Active Claims
              </h3>
              <span className="text-xs font-mono bg-red-100 text-red-700 px-2 py-1 rounded-full font-bold border border-red-200">
                {filteredClaims.length} Cases
              </span>
            </div>
            
            <div className="relative">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search claims..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full text-xs pl-9 pr-3 py-2 bg-white border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-blue/30 focus:border-brand-blue transition-all"
              />
            </div>

            <div className="flex gap-2 text-xs">
              <select
                value={riskFilter}
                onChange={(e) => setRiskFilter(e.target.value)}
                className="flex-1 bg-white border border-slate-300 rounded-lg px-2 py-2 text-[11px] font-semibold text-slate-600 focus:ring-2 focus:ring-brand-blue/30"
              >
                <option value="ALL">All Risk Levels</option>
                <option value="HIGH">High Risk</option>
                <option value="MEDIUM">Medium Risk</option>
                <option value="LOW">Low Risk</option>
              </select>

              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="flex-1 bg-white border border-slate-300 rounded-lg px-2 py-2 text-[11px] font-semibold text-slate-600 focus:ring-2 focus:ring-brand-blue/30"
              >
                <option value="ALL">All Statuses</option>
                <option value="Open">Open</option>
                <option value="Under Review">Under Review</option>
                <option value="Escalated">Escalated</option>
                <option value="Resolved">Resolved</option>
              </select>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto divide-y divide-slate-100 p-2 space-y-1">
            {filteredClaims.map((claim) => {
              const isSelected = activeClaim.claim_id === claim.claim_id;
              return (
                <div
                  key={claim.claim_id}
                  onClick={() => onSelectClaim(claim)}
                  className={`p-3 rounded-xl cursor-pointer transition-all border-2 transform ${
                    isSelected
                      ? 'bg-gradient-to-br from-brand-lightBlue to-cyan-50 border-brand-blue shadow-md scale-[1.02]'
                      : 'bg-white border-transparent hover:bg-slate-50 hover:shadow-sm hover:border-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-mono font-bold text-xs text-brand-blue">{claim.claim_id}</span>
                    <RiskBadge level={claim.risk_level} score={claim.fraud_percentage} />
                  </div>

                  <p className="text-xs font-semibold text-slate-800 truncate mb-2">{claim.provider_name}</p>

                  <div className="flex items-center justify-between text-[11px] text-slate-500">
                    <span className="font-bold text-slate-900">${claim.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                    <StatusBadge status={claim.status} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Pane: Investigation Detail */}
        <div className="lg:col-span-8 bg-white rounded-xl border border-slate-200 shadow-lg flex flex-col h-full overflow-y-auto">
          
          <div className="p-6 bg-gradient-to-r from-slate-50 to-blue-50 border-b border-slate-200">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div>
                <div className="flex items-center gap-3 mb-2">
                  <h3 className="text-xl font-extrabold text-navy-900 font-mono">{activeClaim.claim_id}</h3>
                  <RiskBadge level={activeClaim.risk_level} score={activeClaim.fraud_percentage} />
                  <StatusBadge status={claimStatus} />
                </div>
                <div className="space-y-1 text-xs text-slate-600">
                  <p className="flex items-center gap-2">
                    <Building2 className="w-3.5 h-3.5 text-brand-blue" />
                    <strong className="text-slate-800">{activeClaim.provider_name}</strong> 
                    <span className="font-mono text-slate-500">({activeClaim.provider_id})</span>
                  </p>
                  <p className="flex items-center gap-2">
                    <User className="w-3.5 h-3.5 text-slate-400" />
                    Beneficiary: <span className="font-mono">{activeClaim.beneficiary_id}</span> • 
                    Date: <span className="font-mono">{activeClaim.claim_date}</span>
                  </p>
                </div>
              </div>

              <div className="text-right bg-white p-4 rounded-xl shadow-sm border border-slate-200">
                <span className="text-[11px] font-semibold uppercase text-slate-400 block mb-1">Claim Amount</span>
                <span className="text-3xl font-extrabold text-navy-900 font-mono">
                  ${(activeClaim.amount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </span>
              </div>
            </div>
          </div>

          <div className="p-6">
            <div className="grid grid-cols-1 md:grid-cols-12 gap-6 bg-gradient-to-br from-slate-50 via-blue-50 to-cyan-50 p-6 rounded-2xl border-2 border-blue-200 shadow-inner">
              <div className="md:col-span-4 flex items-center justify-center border-b md:border-b-0 md:border-r border-blue-200 pb-4 md:pb-0">
                <RiskGauge percentage={activeClaim.fraud_percentage || 89} riskLevel={activeClaim.risk_level} size={160} />
              </div>

              <div className="md:col-span-8 flex flex-col justify-between space-y-4">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                      <Zap className="w-4 h-4 text-yellow-500" />
                      Model Prediction Output
                    </span>
                    <span className="text-xs font-mono font-bold bg-navy-900 text-white px-3 py-1 rounded-full">
                      Threshold: 0.50
                    </span>
                  </div>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs mb-4">
                    <div className="bg-white p-3 rounded-xl border-2 border-slate-200 shadow-sm">
                      <span className="text-[10px] text-slate-400 block font-semibold mb-1">PREDICTION</span>
                      <span className="font-bold text-red-600">{activeClaim.fraud_probability >= 0.5 ? 'Potential Fraud' : 'Not Fraud'}</span>
                    </div>
                    <div className="bg-white p-3 rounded-xl border-2 border-slate-200 shadow-sm">
                      <span className="text-[10px] text-slate-400 block font-semibold mb-2">
  PROCEDURES (CPT)
</span>

<div className="flex flex-col gap-1.5">
  <span className="inline-flex w-fit bg-slate-200 border border-slate-300 rounded px-2.5 py-1 text-xs font-mono text-slate-800">
    99214
  </span>

  <span className="inline-flex w-fit bg-slate-200 border border-slate-300 rounded px-2.5 py-1 text-xs font-mono text-slate-800">
    80053
  </span>
</div>
                    </div>
                    <div className="bg-white p-3 rounded-xl border-2 border-slate-200 shadow-sm">
                      <span className="text-[10px] text-slate-400 block font-semibold mb-2">
  DIAGNOSES (ICD-10)
</span>

<div className="flex flex-wrap gap-1.5">
  <span className="inline-flex w-fit bg-slate-200 border border-slate-300 rounded px-2.5 py-1 text-xs font-mono text-slate-800">
    I10
  </span>

  <span className="inline-flex w-fit bg-slate-200 border border-slate-300 rounded px-2.5 py-1 text-xs font-mono text-slate-800">
    E11.9
  </span>
</div>
                    </div>
                    <div className="bg-white p-3 rounded-xl border-2 border-slate-200 shadow-sm">
                      <span className="text-[10px] text-slate-400 block font-semibold mb-1">CLAIM TYPE</span>
                      <span className="font-bold text-slate-800">{activeClaim.claim_type || 'Inpatient'}</span>
                    </div>
                  </div>

                  <div className="bg-white p-4 rounded-xl border-2 border-blue-200 shadow-sm">
                    <p className="text-xs text-slate-600 leading-relaxed italic flex items-start gap-2">
                      <MessageSquare className="w-4 h-4 text-brand-blue mt-0.5 flex-shrink-0" />
                      <span>
                        "This claim has been flagged with a <strong className="text-red-600">{activeClaim.fraud_percentage}% fraud probability</strong> based on abnormal reimbursement scale, high beneficiary claim density, and inpatient/outpatient ratio variance."
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Investigation Tabs */}
          <div className="px-6 pb-6 space-y-4">
            <div className="border-b-2 border-slate-200 flex gap-1 overflow-x-auto">
              {[
                { id: 'intelligence', label: 'Risk Drivers', icon: TrendingUp },
                { id: 'why-flagged', label: 'Why Flagged?', icon: AlertTriangle },
                { id: 'explainability', label: 'SHAP Analysis', icon: Brain },
                { id: 'actions', label: 'Investigation Workflow', icon: Activity },
              ].map(tab => {
                const Icon = tab.icon;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`pb-3 px-4 text-xs font-bold border-b-4 transition-all flex items-center gap-2 whitespace-nowrap ${
                      activeTab === tab.id
                        ? 'border-brand-blue text-brand-blue bg-brand-lightBlue/30'
                        : 'border-transparent text-slate-500 hover:text-slate-800 hover:bg-slate-50'
                    }`}
                  >
                    <Icon className="w-4 h-4" />
                    {tab.label}
                  </button>
                );
              })}
            </div>

            {/* Tab Content */}
            {activeTab === 'intelligence' && (
              <div className="space-y-3 animate-fadeIn">
                <h4 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                  <TrendingUp className="w-4 h-4 text-red-600" />
                  Ranked Anomaly Risk Factors
                </h4>
                <div className="space-y-2">
                  {[
                    { title: 'High Reimbursement Amount', val: `$${(activeClaim.amount || 14250).toLocaleString()}`, desc: 'Exceeds regional peer average by 310%', level: 'HIGH', impact: '+28%' },
                    { title: 'Beneficiary Claim Frequency', val: '6.8 claims/pt', desc: 'Patient claim density is 2.4x expected threshold', level: 'HIGH', impact: '+22%' },
                    { title: 'Inpatient Claim Concentration', val: '42% Share', desc: 'Unusual proportion of inpatient billing for specialty', level: 'MEDIUM', impact: '+16%' },
                    { title: 'Procedure Code Variance', val: activeClaim.procedure_code || 'CPT-99214', desc: 'Frequent billing of high-complexity code combinations', level: 'MEDIUM', impact: '+12%' },
                  ].map((f, i) => (
                    <div key={i} className="flex items-center justify-between p-4 bg-gradient-to-r from-slate-50 to-white rounded-xl border-2 border-slate-200 hover:border-brand-blue hover:shadow-md transition-all">
                      <div className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-red-500 to-red-600 text-white flex items-center justify-center font-bold text-sm shrink-0 mt-0.5 shadow-md">
                          {i + 1}
                        </div>
                        <div>
                          <h5 className="text-sm font-bold text-slate-800">{f.title}</h5>
                          <p className="text-xs text-slate-500">{f.desc}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <span className="text-sm font-bold font-mono text-slate-900 block">{f.val}</span>
                        <span className="text-xs font-mono font-bold text-red-600 bg-red-50 px-2 py-0.5 rounded border border-red-200">{f.impact}</span>
                        <div className="mt-1">
                          <RiskBadge level={f.level} />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'why-flagged' && (
              <div className="p-5 bg-gradient-to-br from-blue-50 to-cyan-50 rounded-2xl border-2 border-blue-200 space-y-3 shadow-inner animate-fadeIn">
                <div className="flex items-center gap-2 text-brand-blue font-bold text-sm">
                  <Sparkles className="w-5 h-5 animate-pulse" />
                  <span>AI Natural Language Rationale</span>
                </div>
                <p className="text-sm text-slate-700 leading-relaxed">
                  "Provider <strong>{activeClaim.provider_name}</strong> has been assigned a high fraud probability of <strong className="text-red-600">{activeClaim.fraud_percentage}%</strong> based on a combination of total reimbursement volume, beneficiary-level claim frequency, and inpatient share patterns. In particular, the average reimbursement per claim exceeds standard regional baselines for procedure code <code className="bg-blue-100 px-1.5 py-0.5 rounded font-mono text-xs">{activeClaim.procedure_code}</code>."
                </p>
                <div className="pt-3 border-t-2 border-blue-200/60 flex items-center justify-between text-xs text-slate-500">
                  <span className="flex items-center gap-1">
                    <Brain className="w-3.5 h-3.5 text-brand-blue" />
                    Model: HistGradientBoostingClassifier
                  </span>
                  <span className="font-mono font-bold text-brand-blue bg-white px-2 py-1 rounded">Threshold: 0.50</span>
                </div>
              </div>
            )}

            {activeTab === 'explainability' && (
              <div className="space-y-5 animate-fadeIn">
                {loadingShap ? (
                  <div className="flex items-center justify-center p-12">
                    <div className="text-center space-y-3">
                      <Brain className="w-12 h-12 text-brand-blue animate-pulse mx-auto" />
                      <p className="text-sm text-slate-600 font-semibold">Loading SHAP explanation...</p>
                    </div>
                  </div>
                ) : shapData ? (
                  <>
                    

                    <div className="bg-white p-6 rounded-2xl border-2 border-slate-300 shadow-md">
                      <div className="flex items-center gap-2 mb-4 pb-3 border-b-2 border-slate-200">
                        <MessageSquare className="w-5 h-5 text-brand-blue" />
                        <h4 className="text-base font-bold text-slate-900 uppercase tracking-wide">Detailed Explanation</h4>
                      </div>
                      
                      <div className="prose prose-sm max-w-none text-slate-700 leading-relaxed space-y-4">
                        {shapData.explanation.split('\n\n').map((paragraph, idx) => {
                          if (!paragraph.trim()) return null;
                          
                          if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
                            return (
                              <h5 key={idx} className="font-extrabold text-navy-900 text-base mt-5 mb-3 flex items-center gap-2">
                                <div className="w-1 h-6 bg-brand-blue rounded"></div>
                                {paragraph.replace(/\*\*/g, '')}
                              </h5>
                            );
                          }
                          
                          if (paragraph.startsWith('•')) {
                            return (
                              <div key={idx} className="ml-4 flex items-start gap-3 mb-3 p-3 bg-blue-50 rounded-lg border-l-4 border-brand-blue">
                                <Zap className="w-4 h-4 text-brand-blue mt-1 flex-shrink-0" />
                                <p 
                                  className="text-sm" 
                                  dangerouslySetInnerHTML={{ 
                                    __html: paragraph.substring(2)
                                      .replace(/\*\*(.+?)\*\*/g, '<strong class="text-navy-900 font-bold">$1</strong>')
                                  }} 
                                />
                              </div>
                            );
                          }
                          
                          return (
                            <p 
                              key={idx} 
                              className="text-sm leading-relaxed text-slate-700"
                              dangerouslySetInnerHTML={{ 
                                __html: paragraph
                                  .replace(/\*\*(.+?)\*\*/g, '<strong class="text-navy-900 font-bold">$1</strong>')
                              }} 
                            />
                          );
                        })}
                      </div>
                    </div>

                    <div>
                      <h4 className="text-sm font-bold text-slate-800 uppercase tracking-wider mb-3 flex items-center gap-2">
                        <TrendingUp className="w-4 h-4 text-red-600" />
                        Feature Contribution Breakdown
                      </h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {shapData.features.map((feature, idx) => (
                          <div key={idx} className="bg-gradient-to-br from-white to-slate-50 p-5 rounded-xl border-2 border-slate-200 hover:border-brand-blue hover:shadow-xl transition-all transform hover:scale-[1.02]">
                            <div className="flex items-start justify-between mb-3">
                              <div className="flex items-center gap-2">
                                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-blue to-cyan-500 text-white flex items-center justify-center font-bold text-sm shadow-md">
                                  {idx + 1}
                                </div>
                                <h5 className="text-sm font-bold text-slate-900">{feature.name.replace(/_/g, ' ')}</h5>
                              </div>
                              <span className={`text-xl font-extrabold font-mono px-3 py-1 rounded-lg shadow-sm ${
                                feature.impact.startsWith('+') ? 'bg-red-100 text-red-700 border-2 border-red-300' : 'bg-green-100 text-green-700 border-2 border-green-300'
                              }`}>
                                {feature.impact}
                              </span>
                            </div>
                            <div className="space-y-2">
                              <div className="flex items-center justify-between text-sm">
                                <span className="text-slate-500 font-medium">Value:</span>
                                <span className="font-mono text-brand-blue font-bold text-base">
                                  {typeof feature.value === 'number' && feature.value > 100 
                                    ? `$${feature.value.toLocaleString()}` 
                                    : feature.value}
                                </span>
                              </div>
                              <p className="text-xs text-slate-600 italic bg-slate-100 p-2 rounded-lg border border-slate-200">
                                {feature.description}
                              </p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-2 border-amber-200 rounded-xl p-5">
                      <div className="flex items-start gap-3">
                        <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <h5 className="font-bold text-sm text-amber-900 mb-2">Key Takeaway</h5>
                          <p className="text-sm text-amber-800 leading-relaxed">
                            The model's prediction is driven by <strong>multiple converging risk factors</strong>. 
                            Each feature contributes incremental evidence, and their combination creates a statistically 
                            significant pattern that matches confirmed fraud cases in the training data.
                          </p>
                        </div>
                      </div>
                    </div>
                  </>
                ) : (
                  <div className="text-center p-12 text-slate-500 bg-slate-50 rounded-xl border-2 border-slate-200">
                    <Brain className="w-16 h-16 mx-auto mb-4 text-slate-300" />
                    <p className="text-sm font-semibold">No SHAP data available for this claim</p>
                  </div>
                )}
              </div>
            )}

            {activeTab === 'actions' && (
              <div className="space-y-4 animate-fadeIn">
                <div className="bg-gradient-to-br from-slate-50 to-blue-50 p-5 rounded-2xl border-2 border-slate-200">
                  <h4 className="text-sm font-bold text-slate-700 uppercase tracking-wider mb-3 flex items-center gap-2">
                    <Activity className="w-4 h-4 text-brand-blue" />
                    Case Status Triage
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {['Open', 'Under Review', 'Escalated', 'Resolved', 'Dismissed'].map(st => (
                      <button
                        key={st}
                        onClick={() => handleStatusChange(st)}
                        className={`text-xs font-bold px-4 py-2 rounded-xl border-2 transition-all transform hover:scale-105 ${
                          claimStatus === st
                            ? 'bg-gradient-to-r from-navy-900 to-slate-800 text-white border-navy-900 shadow-lg'
                            : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                        }`}
                      >
                        {st}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-3">
                  <h4 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                    <FileText className="w-4 h-4 text-slate-600" />
                    Investigator Notes Log
                  </h4>
                  <div className="space-y-2 max-h-48 overflow-y-auto">
                    {notes.map((n, i) => (
                      <div key={i} className="p-4 bg-white rounded-xl border-2 border-slate-200 text-xs space-y-2 hover:shadow-md transition-all">
                        <div className="flex justify-between text-[10px] text-slate-400 font-semibold">
                          <span className="flex items-center gap-1">
                            <User className="w-3 h-3" />
                            {n.author}
                          </span>
                          <span>{n.date}</span>
                        </div>
                        <p className="text-slate-700">{n.text}</p>
                      </div>
                    ))}
                  </div>

                  <form onSubmit={handleAddNote} className="flex gap-2">
                    <input
                      type="text"
                      placeholder="Add investigation case note..."
                      value={newNote}
                      onChange={(e) => setNewNote(e.target.value)}
                      className="flex-1 text-xs border-2 border-slate-300 rounded-xl px-4 py-3 focus:ring-2 focus:ring-brand-blue/30 focus:border-brand-blue transition-all"
                    />
                    <button
                      type="submit"
                      disabled={!newNote.trim()}
                      className="bg-gradient-to-r from-brand-blue to-cyan-500 hover:from-brand-darkBlue hover:to-cyan-600 text-white text-xs font-bold px-5 py-3 rounded-xl disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105 shadow-md"
                    >
                      Add Note
                    </button>
                  </form>
                </div>
              </div>
            )}

          </div>
        </div>
      </div>
    </div>
  );
}
