import React, { useState } from 'react';
import DataTable from '../components/DataTable';
import RiskBadge from '../components/RiskBadge';
import StatusBadge from '../components/StatusBadge';
import { Filter, Download, Plus, Search, ShieldAlert, ArrowUpRight } from 'lucide-react';

export default function Alerts({ alerts, onSelectClaim }) {
  const [riskFilter, setRiskFilter] = useState('ALL');
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [search, setSearch] = useState('');

  const filteredAlerts = alerts.filter(a => {
    const matchesRisk = riskFilter === 'ALL' || a.risk_level === riskFilter;
    const matchesType = typeFilter === 'ALL' || a.claim_type === typeFilter;
    const matchesSearch = 
      a.claim_id.toLowerCase().includes(search.toLowerCase()) ||
      a.provider_name.toLowerCase().includes(search.toLowerCase()) ||
      a.beneficiary_id.toLowerCase().includes(search.toLowerCase());
    return matchesRisk && matchesType && matchesSearch;
  });

  const columns = [
    {
      header: 'Risk',
      accessor: 'risk_level',
      cell: (r) => <RiskBadge level={r.risk_level} score={r.fraud_percentage} />
    },
    {
      header: 'Claim ID',
      accessor: 'claim_id',
      cell: (r) => <span className="font-bold font-mono text-brand-blue">{r.claim_id}</span>
    },
    {
      header: 'Claim Date',
      accessor: 'claim_date',
      cell: (r) => <span className="text-slate-600 font-mono text-[11px]">{r.claim_date}</span>
    },
    {
      header: 'Provider',
      accessor: 'provider_name',
      cell: (r) => (
        <div>
          <p className="font-semibold text-slate-800">{r.provider_name}</p>
          <p className="text-[10px] text-slate-400 font-mono">{r.provider_id}</p>
        </div>
      )
    },
    {
      header: 'Beneficiary',
      accessor: 'beneficiary_id',
      cell: (r) => <span className="font-mono text-slate-600 text-xs">{r.beneficiary_id}</span>
    },
    {
      header: 'Amount',
      accessor: 'amount',
      cell: (r) => <span className="font-bold text-slate-900">${r.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
    },
    {
      header: 'Fraud Prob.',
      accessor: 'fraud_percentage',
      cell: (r) => (
        <span className="font-extrabold text-red-600 font-mono bg-red-50 px-2 py-0.5 rounded border border-red-100">
          {r.fraud_percentage}%
        </span>
      )
    },
    {
      header: 'Status',
      accessor: 'status',
      cell: (r) => <StatusBadge status={r.status} />
    },
    {
      header: 'Action',
      cell: (r) => (
        <button
          onClick={(e) => {
            e.stopPropagation();
            onSelectClaim(r);
          }}
          className="bg-brand-blue hover:bg-brand-darkBlue text-white font-semibold text-xs px-3 py-1.5 rounded flex items-center gap-1 transition-colors"
        >
          <span>Open Case</span>
          <ArrowUpRight className="w-3.5 h-3.5" />
        </button>
      )
    }
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-extrabold text-navy-900">Alerts Queue</h2>
            <span className="bg-red-500 text-white text-xs font-extrabold px-2.5 py-0.5 rounded-full">
              {alerts.length} Active Alerts
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Prioritized Medicare fraud investigation queue generated by Model A (HistGradientBoosting)
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button 
            onClick={() => alert("Alerts queue exported to CSV.")}
            className="bg-white hover:bg-slate-50 text-slate-700 font-semibold text-xs px-3.5 py-2 rounded-lg border border-slate-200 flex items-center gap-1.5 shadow-xs transition-colors"
          >
            <Download className="w-4 h-4 text-slate-500" />
            <span>Export CSV</span>
          </button>
          <button 
            onClick={() => alert("New investigation case initialized.")}
            className="bg-brand-blue hover:bg-brand-darkBlue text-white font-bold text-xs px-3.5 py-2 rounded-lg flex items-center gap-1.5 shadow-xs transition-colors"
          >
            <Plus className="w-4 h-4" />
            <span>Create Case</span>
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 card-shadow flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-1 min-w-[240px]">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Filter alerts by Claim ID, Provider, Beneficiary..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full text-xs pl-9 pr-4 py-2 border border-slate-200 rounded-lg focus:outline-hidden focus:ring-2 focus:ring-brand-blue/20"
            />
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-500">Risk:</span>
            <select
              value={riskFilter}
              onChange={(e) => setRiskFilter(e.target.value)}
              className="text-xs bg-slate-50 border border-slate-200 rounded-lg px-3 py-1.5 font-semibold text-slate-700"
            >
              <option value="ALL">All Risks</option>
              <option value="CRITICAL">Critical Priority</option>
              <option value="HIGH">High Risk</option>
              <option value="MEDIUM">Medium Risk</option>
              <option value="LOW">Low Risk</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-500">Type:</span>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="text-xs bg-slate-50 border border-slate-200 rounded-lg px-3 py-1.5 font-semibold text-slate-700"
            >
              <option value="ALL">All Types</option>
              <option value="Inpatient">Inpatient</option>
              <option value="Outpatient">Outpatient</option>
            </select>
          </div>
        </div>
      </div>

      {/* Main Alerts Data Table */}
      <DataTable
        columns={columns}
        data={filteredAlerts}
        onRowClick={(claim) => onSelectClaim(claim)}
        emptyMessage="No alerts matching selected filters."
      />
    </div>
  );
}
