import React, { useState } from 'react';
import DataTable from '../components/DataTable';
import StatusBadge from '../components/StatusBadge';
import { FileText, Download, Plus, Calendar, Clock, CheckCircle2, RefreshCw } from 'lucide-react';
import { fetchReports, createReport } from '../services/api';

export default function Reports({ reports, onReportCreated }) {
  const [reportList, setReportList] = useState(reports || []);
  const [showModal, setShowModal] = useState(false);
  const [newReportName, setNewReportName] = useState('');
  const [newReportType, setNewReportType] = useState('Investigation Summary');

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!newReportName.trim()) return;

    const created = await createReport({ name: newReportName, type: newReportType });
    setReportList([created, ...reportList]);
    if (onReportCreated) onReportCreated(created);
    setShowModal(false);
    setNewReportName('');
  };

  const columns = [
    {
      header: 'Report Name',
      accessor: 'report_name',
      cell: (r) => (
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-slate-100 text-brand-blue">
            <FileText className="w-4 h-4" />
          </div>
          <div>
            <p className="font-bold text-slate-800">{r.report_name}</p>
            <p className="text-[10px] text-slate-400 font-mono">{r.report_id}</p>
          </div>
        </div>
      )
    },
    {
      header: 'Type',
      accessor: 'type',
      cell: (r) => (
        <span className="text-xs font-semibold px-2.5 py-1 rounded bg-slate-100 text-slate-700 border border-slate-200">
          {r.type}
        </span>
      )
    },
    {
      header: 'Generated By',
      accessor: 'generated_by',
      cell: (r) => <span className="text-xs text-slate-600 font-medium">{r.generated_by}</span>
    },
    {
      header: 'Date',
      accessor: 'date',
      cell: (r) => <span className="font-mono text-xs text-slate-500">{r.date}</span>
    },
    {
      header: 'Status',
      accessor: 'status',
      cell: (r) => <StatusBadge status={r.status} />
    },
    {
      header: 'Actions',
      cell: (r) => (
        <div className="flex items-center gap-2">
          <button
            onClick={() => alert(`Downloading PDF for report ${r.report_id}...`)}
            className="text-brand-blue hover:text-brand-darkBlue font-semibold text-xs flex items-center gap-1"
          >
            <Download className="w-3.5 h-3.5" />
            <span>PDF</span>
          </button>
          <span className="text-slate-300">|</span>
          <button
            onClick={() => alert(`Exporting CSV for report ${r.report_id}...`)}
            className="text-slate-600 hover:text-slate-900 font-semibold text-xs flex items-center gap-1"
          >
            <span>CSV</span>
          </button>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-navy-900 tracking-tight">Reports Archive</h2>
          <p className="text-xs text-slate-500 mt-0.5">
            View and export compliance, anomaly, and provider risk investigation reports
          </p>
        </div>

        <button
          onClick={() => setShowModal(true)}
          className="bg-brand-blue hover:bg-brand-darkBlue text-white font-bold text-xs px-4 py-2.5 rounded-lg flex items-center gap-2 shadow-xs transition-colors"
        >
          <Plus className="w-4 h-4" />
          <span>Generate New Report</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Side: Report History */}
        <div className="lg:col-span-8 space-y-3">
          <h3 className="text-sm font-bold text-navy-900">Generated Reports History</h3>
          <DataTable
            columns={columns}
            data={reportList}
          />
        </div>

        {/* Right Side: Scheduled Reports */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white rounded-xl border border-slate-200 p-5 card-shadow space-y-4">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-navy-900">Scheduled Recurring Reports</h3>
              <span className="text-[10px] font-mono font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded">
                Automated
              </span>
            </div>

            <div className="space-y-3">
              {[
                { title: 'Weekly Fraud Alert Summary', frequency: 'Every Monday 08:00 AM', type: 'Fraud Summary' },
                { title: 'Monthly Anomaly Report', frequency: '1st of every month', type: 'Anomaly' },
                { title: 'Provider Risk Audit Index', frequency: 'Bi-weekly Friday', type: 'Provider Risk' }
              ].map((sch, i) => (
                <div key={i} className="p-3 bg-slate-50 rounded-lg border border-slate-200 space-y-1">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-bold text-slate-800">{sch.title}</span>
                    <span className="text-[10px] font-mono text-slate-400">{sch.type}</span>
                  </div>
                  <div className="flex items-center gap-1.5 text-[11px] text-slate-500">
                    <Clock className="w-3.5 h-3.5 text-brand-blue" />
                    <span>{sch.frequency}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

      </div>

      {/* Generate Report Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 border border-slate-200 space-y-4">
            <h3 className="text-base font-bold text-navy-900">Generate Custom Report</h3>
            <form onSubmit={handleGenerate} className="space-y-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">Report Name</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Q3 Inpatient Provider Fraud Audit"
                  value={newReportName}
                  onChange={(e) => setNewReportName(e.target.value)}
                  className="w-full text-xs border border-slate-300 rounded-lg p-2.5 focus:ring-2 focus:ring-brand-blue/20"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">Report Type</label>
                <select
                  value={newReportType}
                  onChange={(e) => setNewReportType(e.target.value)}
                  className="w-full text-xs border border-slate-300 rounded-lg p-2.5 font-semibold text-slate-700"
                >
                  <option value="Investigation Summary">Investigation Summary</option>
                  <option value="Anomaly">Anomaly Report</option>
                  <option value="Provider Risk">Provider Risk Report</option>
                  <option value="Fraud Summary">Fraud Summary Report</option>
                </select>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 text-xs font-bold text-white bg-brand-blue hover:bg-brand-darkBlue rounded-lg shadow"
                >
                  Generate Report
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
